In [14]:
import cv2 as cv
import numpy as np
from PIL import Image

#Read source image
im = cv.imread('test_1.jpg')

#Four corners of the book in source image
x = np.array([[12, 1132, 1], [12, 2148, 1], [3836, 2156, 1], [3836, 888, 1], [2640, 736, 1], [2340, 520, 1], [2552, 508, 1], [2488, 428, 1],
              [2200, 424, 1], [2036, 276, 1], [1892, 268, 1], [1896, 436, 1], [1596, 440, 1], [1588, 508, 1], [1896, 520, 1], [1908, 720, 1], [1428, 944, 1]])

#Read destination image
im_ = cv.imread('naver_map.png')

#Four corners of the book in destination image
x_ = np.array([[2912, 1464, 1], [3352, 1272, 1], [3380, 980, 1], [2792, 664, 1], [2504, 944, 1], [1956, 964, 1], [1752, 816, 1], [1388, 812, 1],
               [1224, 952, 1], [956, 960, 1], [956, 1096, 1], [1304, 1132, 1], [1384, 1280, 1], [1664, 1244, 1], [1816, 1148, 1], [2496, 1100, 1], [2768, 1212, 1]])

#Calculate Homography
h_,status = cv.findHomography(x,x_)

print(h_)

im_out = cv.warpPerspective(im,h_,(im_.shape[1],im_.shape[0]))
im_out = cv.resize(im_out, (int(im_out.shape[1]/4), int(im_out.shape[0]/4)))

cv.imshow("test", im_out)

im_out = cv.resize(im_out, (int(im_out.shape[1]*4), int(im_out.shape[0]*4)))

im_out = Image.fromarray(im_out)
im_out.save("result.jpeg")


# 새로운 대응점 배열 생성

new_pt = []

for i in range(len(x)):
    pt = x[i]

    new_x = (h_[0][0]*pt[0] + h_[0][1]*pt[1] + h_[0][2]) / (h_[2][0]*pt[0] + h_[2][1]*pt[1] + 1)
    new_y = (h_[1][0]*pt[0] + h_[1][1]*pt[1] + h_[1][2]) / (h_[2][0]*pt[0] + h_[2][1]*pt[1] + 1)
    
    new_pt.append(new_x)
    new_pt.append(new_y)
    
new_pt = np.array(new_pt).reshape(-1,2)

# print("new_pt", new_pt)

cv.waitKey()
cv.destroyAllWindows()

[[-1.02324180e+01 -9.66125512e+01  3.71088613e+04]
 [ 2.18318626e+00 -2.49487913e+01 -1.06682612e+04]
 [-3.65919118e-03 -2.31359313e-02  1.00000000e+00]]


In [18]:
from shapely.geometry import Point, Polygon # 기하학적 물체 표현

detec = [2621,1029]
detec2 = [100,100]
ROI_co = x #횡단보도 꼭지점

ped1_co = Point(detec[0], detec[1])
ped2_co = Point(detec2[0], detec2[1])
ROI = Polygon(ROI_co)

if ped1_co.within(ROI) == 1:
    print("경고! 차도 내 보행자가 위치합니다!")
else:
    print("차도 내 보행자가 없습니다.")

경고! 차도 내 보행자가 위치합니다!


In [ ]:
# 검출 결과 list
ped = [[100,100], [600,600], [1100,1100], [1600,1600], [2100,2100]]
veh = [[200,200], [700,700], [1200,1200], [1700,1700], [2200,2200]]
moto = [[300,300], [800,800], [1300,300], [1800,1800], [2300,2300]]
cycle = [[400,400], [900,200], [1400,1400], [1900,1900], [2400,2400]]
kick = [[500,500], [1000,1000], [1500,1500], [2000,2000], [2500,2500]]



In [2]:
# 차도 범위 내 위치여부 판단

# def is_inside(polygon, point):
    
#     def cross(p1, p2):
#         x1, y1 = p1
#         x2, y2 = p2
        
#         if y1 - y2 == 0:
#             if y1 == point[1]:
#                 if min(x1, x2) <= point[0] <= max(x1, x2):
#                     return 1, True
#             return 0, False
        
#         if x1 - x2 == 0:
#             if min(y1, y2) <= point[1] <= max(y1, y2):
#                 if point[0] <= max(x1, x2):
#                     return 1, point[0] == max(x1, x2)
#             return 0, False
        
#         a = (y1 - y2) / (x1 - x2)
#         b = y1 - x1 * a
#         x = (point[1] - b) / a
#         if point[0] <= x:
#             if min(y1, y2) <= point[1] <= max(y1, y2):
#                 return 1, point[0] == x or point[1] in (y1, y2)
#         return 0, False
    
#     cross_points = 0
#     for x in range(len(polygon)):
#         num, on_line = cross(polygon[x], polygon[x-1])
#         if on_line:
#             return True
#         cross_points += num
    
#     return cross_points % 2

In [8]:
# 차도 내 보행자 위치 여부 출력

# polygon = new_pt
# point = [2621,1029] # 테스트할 좌표

# if is_inside(polygon, point) == 1:
#     print("경고! 차도 내 보행자가 위치합니다!")
# else:
#     print("차도 내 보행자가 없습니다.")

경고! 차도 내 보행자가 위치합니다!


In [49]:
cv.waitKey()
cv.destroyAllWindows()